### ISSUE TITLE
Angular Twist Covariance always 0

### ISSUE THREAD

**Issue by TheDelus** [fixposition/fixposition_driver#79]
Hello,

I noticed that in the odometry msgs the covariance for the angular twist is always 0. Why?

```
header:
  stamp:
    sec: 1737039030
    nanosec: 30000000
  frame_id: FP_ENU0
child_frame_id: FP_POI
pose:
  pose:
    position:
      x: 647.5685
      y: 183.7218
      z: 0.3091
    orientation:
      x: -0.999542
      y: 0.021723
      z: 0.019087
      w: -0.008953
  covariance:
  - 0.0021
  - -0.0
  - 0.00055
  - 0.0
  - 0.0
  - 0.0
  - -0.0
  - 0.00166
  - 6.0e-05
  - 0.0
  - 0.0
  - 0.0
  - 0.00055
  - 6.0e-05
  - 0.00271
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.00058
  - -8.0e-05
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - -8.0e-05
  - 0.0001
  - 1.0e-05
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0e-05
  - 7.0e-05
twist:
  twist:
    linear:
      x: -6.1946
      y: 0.031
      z: 0.3118
    angular:
      x: -0.02149
      y: 0.0275
      z: -0.01059
  covariance:
  - 0.00697
  - 4.0e-05
  - -0.00104
  - 0.0
  - 0.0
  - 0.0
  - 4.0e-05
  - 0.00535
  - -0.00022
  - 0.0
  - 0.0
  - 0.0
  - -0.00104
  - -0.00022
  - 0.00533
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
```
